# Generated by Django 3.2.7 on 2021-09-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('book_author', models.CharField(max_length=128)),
                ('publisher', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('release_date', models.DateField()),
                ('created_at', models.DateField()),
                ('updated_at', models.DateField()),
                ('content', models.TextField()),
            ],
        ),
    ]
